# waybar
bar {
  swaybar_command waybar
}

# auto commands
exec nm-applet
exec_always kanshi
exec swaync
exec mpd-mpris
exec swayidle -w
exec blueman-applet
exec emacs --daemon
exec foot --server
exec XDG_CURRENT_DESKTOP=sway
exec --no-startup-id /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
exec "dbus-update-activation-environment --systemd --all "
exec "dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway "
exec  wl-paste --type text --watch cliphist store
exec  wl-paste --type image --watch cliphist store
exec_always autotiling
exec_always /home/samarth/.config/custom_scripts/auto_start.sh
exec foot --server
exec_always sh -c "killall awww-daemon ; awww-daemon && awww restore"
# exec_always killall awww-daemon
# exec_always awww-daemon
# exec_always awww restore
